# Generated by Django 5.2.5 on 2025-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('meal_planner', 'Meal Planner'), ('cleaning_schedule', 'Cleaning Schedule'), ('stickers', 'Digital Stickers'), ('habit_tracker', 'Habit Tracker')], max_length=50),
        ),
    ]
